# Generated by Django 3.2.12 on 2022-05-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Order Received', 'Order Received'), ('Baking-', 'Baked-0'), ('Baked-1', 'Baked-2'), ('Out for delivery', 'Out for delivery'), ('Order received', 'Order received')], default='Order Received', max_length=100),
        ),
    ]
